services:
  komodo-import:
    image: foxxmd/komodo-import:latest
    restart: no
    volumes:
      ## Parent directory where all subfolders are compose projects
      - /home/dan/komodo/stacks:/filesOnServer
    environment:
      ## Same as mounted directory above
      - HOST_DIR=/home/dan/komodo/stacks
      ## Determines what sources to generate Stacks from
      - STACKS_FROM=dir ## Generate stacks from subfolders in directory
      ## Name of Server for this machine, in Komodo
      - SERVER_NAME=tank-prime
      - WRITE_ENV=true ##Write the contents of found .env files to Komodo Environment. Likely want this as true.
      - COMPOSE_FILE_GLOB=**/{compose,docker-compose}*.y?(a)ml ##The glob pattern to use for finding files for Files Paths in Stack config
      - ENV_FILE_GLOB=**/.env  ##The glob pattern to use for finding files for Additional Env Files in Stack config
#      - KOMODO_ENV_NAME=.komodoenv ##	If existing .env files are found, and WRITE_ENV=false, then this name will be used for the .env that Komodo writes using its own Environment section
      

      ## Configuration for interacting with Komodo API
      - KOMODO_URL=https://komodo.stankytanky.org
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - OUTPUT_API_SYNC=true #Create Sync Resource in Komodo
      - PUID=1000
      - PGID=1000
